#!/bin/bash

if [ "$1" = "run" ]; then
	sudo bundle exec jekyll serve
elif [ "$1" = "build" ]; then
	sudo bundle exec jekyll build
elif [ "$1" = "update" ]; then
	./script build
	sudo cp -r _site/* ../tmp/bioloid.github.io/
	cd ../tmp/bioloid.github.io
	git add .
	git rm script 
	git rm README.md
	git commit -m "Update: $2"
	git push
fi
